import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Download, Share2, FileText, Mail } from 'lucide-react';
import { RiskResult, PatientData } from '@/lib/riskCalculator';
import { useToast } from '@/hooks/use-toast';

interface ActionsCardProps {
  result?: RiskResult | null;
  patient?: PatientData | null;
}

export function ActionsCard({ result, patient }: ActionsCardProps) {
  const { toast } = useToast();

  const handleDownloadReport = () => {
    if (!result || !patient) {
      toast({
        title: "No data available",
        description: "Please calculate a risk assessment first.",
        variant: "destructive",
      });
      return;
    }

    const reportContent = `
╔══════════════════════════════════════════════════════════════════════╗
║           MEDPREDICT - CARDIOVASCULAR RISK ASSESSMENT REPORT         ║
╚══════════════════════════════════════════════════════════════════════╝

Report Generated: ${new Date().toLocaleString()}
Model Version: v2.4 (XGBoost)
Confidence Interval: 95%

══════════════════════════════════════════════════════════════════════
                         PATIENT INFORMATION
══════════════════════════════════════════════════════════════════════

Patient ID:        ${patient.patientId}
Age:               ${patient.age} years
Gender:            ${patient.sex}
Assessment Date:   ${new Date().toLocaleDateString()}

══════════════════════════════════════════════════════════════════════
                        CLINICAL MEASUREMENTS
══════════════════════════════════════════════════════════════════════

Resting Blood Pressure:    ${patient.restingBP} mmHg
Total Cholesterol:         ${patient.cholesterol} mg/dL
Maximum Heart Rate:        ${patient.maxHeartRate} bpm
ST Depression:             ${patient.stDepression} mm
Chest Pain Type:           ${patient.chestPainType}
ST Slope:                  ${patient.stSlope}
Exercise-Induced Angina:   ${patient.exerciseAngina ? 'Yes' : 'No'}
Fasting Blood Sugar >120:  ${patient.fastingBloodSugar ? 'Yes' : 'No'}

══════════════════════════════════════════════════════════════════════
                        RISK ASSESSMENT RESULT
══════════════════════════════════════════════════════════════════════

RISK LEVEL:       ${result.riskLevel.toUpperCase()}
PROBABILITY:      ${Math.round(result.probability * 100)}%

Interpretation:
${result.interpretation}

══════════════════════════════════════════════════════════════════════
                  FEATURE IMPORTANCE (SHAP ANALYSIS)
══════════════════════════════════════════════════════════════════════

${result.featureContributions.map(f => 
  `${f.feature.padEnd(20)} ${f.impact >= 0 ? '+' : ''}${f.impact.toFixed(2).padStart(6)} | ${f.description}`
).join('\n')}

══════════════════════════════════════════════════════════════════════
                       CLINICAL THRESHOLDS
══════════════════════════════════════════════════════════════════════

${'Metric'.padEnd(20)} ${'Patient'.padEnd(15)} ${'Target'.padEnd(15)} Status
${'-'.repeat(65)}
${result.clinicalThresholds.map(t => 
  `${t.metric.padEnd(20)} ${t.patientValue.padEnd(15)} ${t.clinicalTarget.padEnd(15)} ${t.status}`
).join('\n')}

══════════════════════════════════════════════════════════════════════
                        RECOMMENDATIONS
══════════════════════════════════════════════════════════════════════

${result.riskLevel === 'High' ? `
⚠️  HIGH RISK - IMMEDIATE ACTION REQUIRED

1. Schedule urgent cardiovascular consultation
2. Consider stress testing and echocardiography
3. Review and optimize medication regimen
4. Implement aggressive lifestyle modifications
5. Schedule follow-up within 2 weeks
` : result.riskLevel === 'Medium' ? `
⚡ MODERATE RISK - MONITORING REQUIRED

1. Schedule follow-up cardiovascular assessment
2. Implement lifestyle modifications (diet, exercise)
3. Monitor blood pressure regularly
4. Consider lipid management optimization
5. Reassess risk in 3 months
` : `
✅ LOW RISK - PREVENTIVE CARE

1. Continue current preventive measures
2. Maintain healthy lifestyle habits
3. Annual cardiovascular screening recommended
4. Monitor for any symptom changes
5. Regular exercise and balanced diet
`}

══════════════════════════════════════════════════════════════════════

DISCLAIMER: This report is generated by an AI-powered prediction system
and should be used as a clinical decision support tool only. Final medical
decisions should be made by qualified healthcare professionals based on
comprehensive patient evaluation.

Generated by MedPredict AI System v2.4
© ${new Date().getFullYear()} MedPredict Healthcare Solutions
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Risk_Report_${patient.patientId}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Report Downloaded",
      description: "Full risk assessment report has been saved.",
    });
  };

  const handleShareWithPatient = () => {
    if (!result || !patient) {
      toast({
        title: "No data available",
        description: "Please calculate a risk assessment first.",
        variant: "destructive",
      });
      return;
    }

    const subject = `Your Cardiovascular Risk Assessment - ${patient.patientId}`;
    const body = `
Dear Patient,

Your cardiovascular risk assessment has been completed.

Risk Level: ${result.riskLevel}
Probability Score: ${Math.round(result.probability * 100)}%

${result.interpretation}

Please schedule a follow-up appointment to discuss these results in detail.

Best regards,
Your Healthcare Team
    `.trim();

    const mailtoUrl = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(mailtoUrl);

    toast({
      title: "Email Client Opened",
      description: "A draft email has been prepared for sharing.",
    });
  };

  return (
    <Card className="border bg-card">
      <CardHeader className="pb-2">
        <CardTitle className="flex items-center gap-2 text-lg">
          <FileText className="w-5 h-5 text-primary" />
          Care Actions & Reports
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <p className="text-sm text-muted-foreground">
          Export a clear summary with top contributors and clinical recommendations for the care team or patient.
        </p>

        <Button 
          variant="default" 
          className="w-full"
          onClick={handleDownloadReport}
        >
          <Download className="w-4 h-4 mr-2" />
          Download Full Report
        </Button>

        <Button 
          variant="outline" 
          className="w-full"
          onClick={handleShareWithPatient}
        >
          <Mail className="w-4 h-4 mr-2" />
          Share with Patient
        </Button>
      </CardContent>
    </Card>
  );
}
