import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { FileText, Download, Calendar, TrendingUp, Users, AlertTriangle, PieChart } from 'lucide-react';

export function ReportsPage() {
  const [selectedPeriod, setSelectedPeriod] = useState('month');

  const stats = {
    totalAssessments: 156,
    highRiskPatients: 42,
    mediumRiskPatients: 67,
    lowRiskPatients: 47,
    averageRisk: 0.52,
  };

  const recentReports = [
    { id: 'RPT-001', name: 'Monthly Risk Summary - January 2024', date: '2024-01-31', type: 'Summary' },
    { id: 'RPT-002', name: 'High Risk Patient Alert Report', date: '2024-01-28', type: 'Alert' },
    { id: 'RPT-003', name: 'Weekly Assessment Trends', date: '2024-01-21', type: 'Trend' },
    { id: 'RPT-004', name: 'Quarterly Performance Analysis', date: '2024-01-15', type: 'Analysis' },
  ];

  const handleDownloadReport = (reportId: string, reportName: string) => {
    // Generate a simple text report
    const reportContent = `
MEDPREDICT HEALTH RISK PREDICTION REPORT
=========================================
Report ID: ${reportId}
Report Name: ${reportName}
Generated: ${new Date().toLocaleString()}

SUMMARY STATISTICS
------------------
Total Assessments: ${stats.totalAssessments}
High Risk Patients: ${stats.highRiskPatients} (${Math.round(stats.highRiskPatients/stats.totalAssessments*100)}%)
Medium Risk Patients: ${stats.mediumRiskPatients} (${Math.round(stats.mediumRiskPatients/stats.totalAssessments*100)}%)
Low Risk Patients: ${stats.lowRiskPatients} (${Math.round(stats.lowRiskPatients/stats.totalAssessments*100)}%)
Average Risk Score: ${Math.round(stats.averageRisk*100)}%

KEY FINDINGS
------------
- ${stats.highRiskPatients} patients require immediate cardiovascular intervention
- Age and chest pain type are the most significant risk factors
- Blood pressure management remains a priority area

RECOMMENDATIONS
---------------
1. Schedule follow-up appointments for all high-risk patients
2. Implement lifestyle modification programs
3. Review medication protocols for hypertensive patients
4. Continue monitoring medium-risk patients quarterly

=========================================
Generated by MedPredict AI System v2.4
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${reportId}_${reportName.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">Reports & Analytics</h2>
          <p className="text-muted-foreground">View insights and download comprehensive reports</p>
        </div>
        <div className="flex items-center gap-3">
          <Select value={selectedPeriod} onValueChange={setSelectedPeriod}>
            <SelectTrigger className="w-40">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="week">This Week</SelectItem>
              <SelectItem value="month">This Month</SelectItem>
              <SelectItem value="quarter">This Quarter</SelectItem>
              <SelectItem value="year">This Year</SelectItem>
            </SelectContent>
          </Select>
          <Button onClick={() => handleDownloadReport('RPT-NEW', 'Custom Report')}>
            <Download className="w-4 h-4 mr-2" />
            Generate Report
          </Button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Total Assessments</p>
                <p className="text-3xl font-bold">{stats.totalAssessments}</p>
              </div>
              <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center">
                <Users className="w-6 h-6 text-primary" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">High Risk Patients</p>
                <p className="text-3xl font-bold text-risk-high">{stats.highRiskPatients}</p>
              </div>
              <div className="w-12 h-12 rounded-full bg-risk-high/10 flex items-center justify-center">
                <AlertTriangle className="w-6 h-6 text-risk-high" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Average Risk Score</p>
                <p className="text-3xl font-bold">{Math.round(stats.averageRisk * 100)}%</p>
              </div>
              <div className="w-12 h-12 rounded-full bg-risk-medium/10 flex items-center justify-center">
                <TrendingUp className="w-6 h-6 text-risk-medium" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Low Risk Patients</p>
                <p className="text-3xl font-bold text-risk-low">{stats.lowRiskPatients}</p>
              </div>
              <div className="w-12 h-12 rounded-full bg-risk-low/10 flex items-center justify-center">
                <PieChart className="w-6 h-6 text-risk-low" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Risk Distribution Chart */}
      <Card>
        <CardHeader>
          <CardTitle>Risk Distribution</CardTitle>
          <CardDescription>Patient distribution by risk category</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex items-center gap-8">
            <div className="flex-1 space-y-4">
              <div>
                <div className="flex justify-between mb-1">
                  <span className="text-sm font-medium">High Risk</span>
                  <span className="text-sm text-muted-foreground">{stats.highRiskPatients} patients ({Math.round(stats.highRiskPatients/stats.totalAssessments*100)}%)</span>
                </div>
                <div className="h-3 rounded-full bg-muted overflow-hidden">
                  <div className="h-full bg-risk-high rounded-full" style={{ width: `${stats.highRiskPatients/stats.totalAssessments*100}%` }} />
                </div>
              </div>
              <div>
                <div className="flex justify-between mb-1">
                  <span className="text-sm font-medium">Medium Risk</span>
                  <span className="text-sm text-muted-foreground">{stats.mediumRiskPatients} patients ({Math.round(stats.mediumRiskPatients/stats.totalAssessments*100)}%)</span>
                </div>
                <div className="h-3 rounded-full bg-muted overflow-hidden">
                  <div className="h-full bg-risk-medium rounded-full" style={{ width: `${stats.mediumRiskPatients/stats.totalAssessments*100}%` }} />
                </div>
              </div>
              <div>
                <div className="flex justify-between mb-1">
                  <span className="text-sm font-medium">Low Risk</span>
                  <span className="text-sm text-muted-foreground">{stats.lowRiskPatients} patients ({Math.round(stats.lowRiskPatients/stats.totalAssessments*100)}%)</span>
                </div>
                <div className="h-3 rounded-full bg-muted overflow-hidden">
                  <div className="h-full bg-risk-low rounded-full" style={{ width: `${stats.lowRiskPatients/stats.totalAssessments*100}%` }} />
                </div>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Recent Reports */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary" />
            Recent Reports
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {recentReports.map((report) => (
              <div key={report.id} className="flex items-center justify-between p-4 rounded-lg border bg-card hover:bg-accent/50 transition-colors">
                <div className="flex items-center gap-4">
                  <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                    <FileText className="w-5 h-5 text-primary" />
                  </div>
                  <div>
                    <p className="font-medium">{report.name}</p>
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <Calendar className="w-3 h-3" />
                      {report.date}
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <Badge variant="outline">{report.type}</Badge>
                  <Button variant="outline" size="sm" onClick={() => handleDownloadReport(report.id, report.name)}>
                    <Download className="w-4 h-4 mr-2" />
                    Download
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
